import { Cluster } from './types';

export const clusters: Cluster[] = [
  {
    id: 'foundations-of-privacy',
    name: 'Foundations of Privacy',
    tagline: 'Personal boundaries and meaningful choice',
    description: 'Explore the dimensions of privacy, appropriate information flows, and the freedom to make personal choices.',
    color: '#176b87',
    accentBg: '#f0f7fa',
    borderColor: '#bad5df',
    centerPos: { x: 300, y: 220 },
  },
  {
    id: 'gdpr-data-governance',
    name: 'GDPR & Data Governance',
    tagline: 'Personal data, rights, and lawful processing',
    description: 'Understand which data are personal, what processing requires, and when automated decisions need safeguards.',
    color: '#4a5c9e',
    accentBg: '#f2f4fa',
    borderColor: '#cbd2e7',
    centerPos: { x: 1050, y: 180 },
  },
  {
    id: 'differential-privacy',
    name: 'Differential Privacy',
    tagline: 'What the guarantee protects—and its limits',
    description: 'Learn how randomized releases limit disclosure, how privacy budgets work, and why raw data still need protection.',
    color: '#704c9a',
    accentBg: '#f6f2fa',
    borderColor: '#d8cbe7',
    centerPos: { x: 1800, y: 260 },
  },
  {
    id: 'transparency-explanation',
    name: 'Transparency & Explanation',
    tagline: 'Understanding and challenging decisions',
    description: 'Compare transparency, interpretability, and explanation, then ask whether a decision can actually be justified.',
    color: '#176d64',
    accentBg: '#eef7f4',
    borderColor: '#c2dfd6',
    centerPos: { x: 1800, y: 920 },
  },
  {
    id: 'responsibility-dual-use',
    name: 'Responsibility & Dual Use',
    tagline: 'Anticipating harm and knowing who must act',
    description: 'Explore responsibility before and after harm, potential misuse, precaution, and shared duties across teams.',
    color: '#95601d',
    accentBg: '#fbf6ee',
    borderColor: '#e7d6bc',
    centerPos: { x: 1080, y: 980 },
  },
  {
    id: 'bias-measurement',
    name: 'Bias & Measurement',
    tagline: 'Who gets measured and what gets missed',
    description: 'Follow bias through sampling, labels, model choices, and feedback loops. Read alongside fairness in Chapter 6.',
    color: '#a14e58',
    accentBg: '#fcf2f3',
    borderColor: '#ebcdd2',
    centerPos: { x: 320, y: 920 },
  },
  {
    id: 'fairness-justice',
    name: 'Fairness & Justice',
    tagline: 'Fair treatment beyond a model score',
    description: 'Compare equality, equity, and justice, examine fairness metrics, and consider the institutions around a model.',
    color: '#984873',
    accentBg: '#faf1f6',
    borderColor: '#e5c8d8',
    centerPos: { x: 340, y: 1650 },
  },
  {
    id: 'high-stakes-applications',
    name: 'Medicine & Predictive Policing',
    tagline: 'Decisions that affect health and liberty',
    description: 'Apply privacy, fairness, and responsibility to medical prediction and policing, including oversight and routes to challenge.',
    color: '#347452',
    accentBg: '#f0f7f0',
    borderColor: '#c9dfca',
    centerPos: { x: 1250, y: 1680 },
  },
  {
    id: 'ethical-reasoning',
    name: 'Ethical Reasoning',
    tagline: 'How to think about what we ought to do',
    description: 'Distinguish facts from ethical judgments, examine moral intuitions and principles, and recognize genuine ethical dilemmas.',
    color: '#5b7a3d',
    accentBg: '#f4f7f0',
    borderColor: '#c8d8b8',
    centerPos: { x: 2600, y: 200 },
  },
  {
    id: 'ethical-frameworks',
    name: 'Ethical Frameworks',
    tagline: 'Consequentialism, deontology, virtue and contract',
    description: 'Compare the major ethical theories that inform debates about data, privacy, and algorithmic decision-making.',
    color: '#8b6914',
    accentBg: '#faf6ec',
    borderColor: '#e0d2a8',
    centerPos: { x: 2600, y: 800 },
  },
  {
    id: 'decision-making',
    name: 'Human Decision-Making',
    tagline: 'Bounded rationality, heuristics and biases',
    description: 'Understand how cognitive limits, shortcuts and biases shape the decisions that data systems are built to support or replace.',
    color: '#6a4f8b',
    accentBg: '#f5f2f8',
    borderColor: '#d2c6e0',
    centerPos: { x: 2600, y: 1400 },
  },
  {
    id: 'influence-and-nudging',
    name: 'Influence & Choice Architecture',
    tagline: 'Nudges, hypernudges and algorithmic steering',
    description: 'Examine how data-driven systems shape what people see, choose, and do — and the critiques of these mechanisms.',
    color: '#b5651d',
    accentBg: '#faf4ec',
    borderColor: '#e2cdb0',
    centerPos: { x: 1800, y: 1600 },
  },
  {
    id: 'threat-modeling',
    name: 'Threat Modeling & PETs',
    tagline: 'Security, privacy threats and technical safeguards',
    description: 'Distinguish security from privacy, use STRIDE and LINDDUN to find threats, and choose privacy-enhancing technologies that match the problem.',
    color: '#2d6a4f',
    accentBg: '#eef6f2',
    borderColor: '#b8d8c8',
    centerPos: { x: 600, y: 1600 },
  },
];
