import { Concept } from './types';

export const concepts: Concept[] = [
  // ======================================================================
  // 1. WHY PRIVACY MATTERS
  // ======================================================================
  {
    id: 'spatial-privacy',
    slug: 'spatial-privacy',
    title: 'Spatial / Local Privacy',
    clusterId: 'foundations-of-privacy',
    conciseDefinition: 'Protection against inappropriate access to one’s body, home, room, or other physical spaces.',
    expandedExplanation: 'Privacy concerns appropriate boundaries around access to persons, places, information, and decisions. Spatial or local privacy safeguards physical and domestic sanctuaries from uninvited physical or sensory intrusion. The spatial, informational, and decisional dimensions interact: for example, a camera in the home invades spatial privacy and simultaneously creates personal data.',
    whyItMatters: 'Physical and domestic sanctuaries provide spaces relatively insulated from observation, allowing recuperation, intimacy, and unmonitored human relationships.',
    example: 'A camera placed in a private home or bedroom invades spatial privacy and creates digital data streams.',
    limitationsOrMisconceptions: 'Spatial privacy is not separate from digital data science; modern sensors and surveillance devices bridge physical spaces and digital profiles.',
    keywords: ['spatial privacy', 'local privacy', 'physical sanctuary', 'observation', 'intrusion'],
    sourceIds: ['S1'],
    chapterId: 'ch1',
    position: { x: 140, y: 120 },
  },
  {
    id: 'informational-privacy',
    slug: 'informational-privacy',
    title: 'Informational Privacy',
    clusterId: 'foundations-of-privacy',
    conciseDefinition: 'Appropriate limits on collecting, inferring, using, and disclosing information about a person.',
    expandedExplanation: 'Informational privacy governs appropriate boundaries on personal data flows. Crucially, this includes information others can infer through predictive modeling or aggregation, not just data a person explicitly shared. It interacts directly with decisional privacy: a prediction about reproductive health may affect both informational boundaries and decisional freedom.',
    whyItMatters: 'Predictive data science routinely infers sensitive attributes (such as medical risk or political opinions) from secondary behavioral trails without direct user disclosure.',
    example: 'A platform inferring a user’s undisclosed health condition or pregnancy status from browsing patterns and retail transaction history.',
    limitationsOrMisconceptions: 'Informational privacy differs from confidentiality: confidentiality specifically concerns restricting unauthorized access to agreed secrets in relationships, whereas privacy concerns the broader appropriate treatment of people and their data.',
    keywords: ['informational privacy', 'inference', 'disclosure', 'collection', 'profiling'],
    sourceIds: ['S1'],
    chapterId: 'ch1',
    position: { x: 380, y: 120 },
  },
  {
    id: 'decisional-privacy',
    slug: 'decisional-privacy',
    title: 'Decisional Privacy',
    clusterId: 'foundations-of-privacy',
    conciseDefinition: 'Scope to make intimate or life-shaping choices without unjustified interference.',
    expandedExplanation: 'Decisional privacy protects personal autonomy in making fundamental life choices. While legal traditions often emphasize protection against government interference, the full ethical concept encompasses constraints imposed by employers, platforms, algorithmic nudges, and other private actors.',
    whyItMatters: 'Algorithmic targeting, behavioral steering, and personalized choice architectures can subtly constrain human choices and erode autonomous deliberation.',
    example: 'Micro-targeted digital advertising or platform choice architectures designed to manipulate user voting decisions or healthcare choices.',
    limitationsOrMisconceptions: 'Decisional privacy is not limited to government interference; platforms and commercial entities can also unjustifiably constrain choices.',
    keywords: ['decisional privacy', 'autonomy', 'interference', 'choice', 'nudging'],
    sourceIds: ['S1'],
    chapterId: 'ch1',
    position: { x: 260, y: 240 },
  },
  {
    id: 'access-account',
    slug: 'access-account',
    title: 'Access Account of Privacy',
    clusterId: 'foundations-of-privacy',
    conciseDefinition: 'The philosophical account holding that privacy diminishes when others actually obtain access to you or information about you.',
    expandedExplanation: 'Under the access account, privacy is evaluated by the degree of non-access. If another party observes or acquires information about a person, privacy is diminished regardless of whether the person consented or whether the observer is trustworthy.',
    whyItMatters: 'Clarifies that even fully authorized disclosures reduce descriptive privacy because others now possess the information.',
    example: 'A person who willingly publishes their genetic sequence or medical history to a research repository has authorized the disclosure, but has still lost privacy in the sense that others now know the information.',
    limitationsOrMisconceptions: 'These are philosophical accounts, not tests for GDPR compliance. Do not state that access is categorically "stricter" in all respects without specifying what privacy interest and scenario you mean.',
    keywords: ['access account', 'non-access', 'exposure', 'philosophical account'],
    sourceIds: ['S1'],
    chapterId: 'ch1',
    position: { x: 120, y: 380 },
  },
  {
    id: 'control-account',
    slug: 'control-account',
    title: 'Control Account of Privacy',
    clusterId: 'foundations-of-privacy',
    conciseDefinition: 'The philosophical account holding that privacy concerns your effective authority over whether, how, and by whom access occurs.',
    expandedExplanation: 'Under the control account, privacy is framed as self-determination and authority over one’s personal boundaries. Sharing information under chosen permissions does not eliminate privacy, provided the individual retains effective governance over access.',
    whyItMatters: 'Underpins user consent, access settings, and data-rights mechanisms in digital platforms.',
    example: 'A patient granting a trusted specialist revocable access to specific diagnostic scans exercises control over who accesses the data.',
    limitationsOrMisconceptions: 'Control without knowledge or real power may be illusory. Forcing users to accept unread terms of service without viable alternatives does not constitute meaningful control.',
    keywords: ['control account', 'authority', 'consent', 'self-determination'],
    sourceIds: ['S1'],
    chapterId: 'ch1',
    position: { x: 400, y: 380 },
  },
  {
    id: 'contextual-integrity',
    slug: 'contextual-integrity',
    title: 'Contextual Integrity',
    clusterId: 'foundations-of-privacy',
    conciseDefinition: 'The framework asserting that privacy norms govern context-specific flows of information, not a blanket ban on sharing.',
    expandedExplanation: 'Contextual integrity asks: Who is the data subject? Who sends information? Who receives it? What kind of information? Under what conditions or transmission principle? Sharing a medical diagnosis with a treating physician differs completely from selling it to an advertiser, even though the data are identical.',
    whyItMatters: 'Demonstrates that privacy violations arise from inappropriate contextual transfers and transmission principles, not from the mere act of sharing data.',
    example: 'A patient sharing a diagnosis with a treating physician respects healthcare context norms; transferring that identical record to an advertiser breaches contextual integrity.',
    limitationsOrMisconceptions: 'Contextual integrity is not a demand for total secrecy or a ban on data sharing; it requires data flows to respect context-specific norms and purposes.',
    keywords: ['contextual integrity', 'transmission principle', 'information flow', 'norms', 'nissenbaum'],
    sourceIds: ['S1'],
    chapterId: 'ch1',
    position: { x: 260, y: 480 },
  },
  {
    id: 'chilling-effect',
    slug: 'chilling-effect',
    title: 'Chilling Effect & Legal Chilling',
    clusterId: 'foundations-of-privacy',
    conciseDefinition: 'Conduct discouraged by anticipated sanctions, or self-censorship induced by pervasive monitoring and profiling.',
    expandedExplanation: 'In a legal context, a chilling effect means conduct is discouraged by anticipated sanctions or burdens even without an actual penalty. In privacy discussions, the term also covers self-censorship induced by monitoring and profiling; it is not limited to threatened legal sanctions. People may refrain from lawful speech, experimentation, or dissent because they expect observation or consequences.',
    whyItMatters: 'Anticipated monitoring can discourage participation, dissent, or inquiry even without a formal sanction. The effect depends on the context.',
    example: 'Individuals refraining from searching for sensitive health questions or reading controversial political literature because web queries are tracked.',
    limitationsOrMisconceptions: 'Evidence and context matter; do not present a universal psychological effect as an invariant law, and do not restrict chilling effects only to criminal legal sanctions.',
    keywords: ['chilling effect', 'legal chilling', 'self-censorship', 'surveillance', 'deterrence'],
    sourceIds: ['S1'],
    chapterId: 'ch1',
    position: { x: 120, y: 560 },
  },
  {
    id: 'information-asymmetry',
    slug: 'information-asymmetry',
    title: 'Information Asymmetry',
    clusterId: 'foundations-of-privacy',
    conciseDefinition: 'A structural condition where one actor has significantly more relevant information than another, reducing the latter’s ability to assess risks and choose freely.',
    expandedExplanation: 'When one actor possesses vast behavioral data and predictive models while the other possesses little knowledge of the evaluation process, the latter cannot freely evaluate risks. Withholding, distorting, or falsifying information is an aggravated case; asymmetry can also arise without deliberate deception. Privacy notices, understandable explanations, and contestability partly address it, but notices alone rarely remove unequal power.',
    whyItMatters: 'Standard privacy notices fail to equalize power when complex algorithmic systems maintain massive information advantages over users.',
    example: 'An online platform scoring loan applicants based on opaque behavioral metadata while the applicant is given only an uninformative rejection notice.',
    limitationsOrMisconceptions: 'Information asymmetry is not caused only by fraudulent deception; it arises naturally from complex systemic processing and cannot be solved by notices alone.',
    keywords: ['information asymmetry', 'power imbalance', 'risk assessment', 'privacy notice', 'contestability'],
    sourceIds: ['S1', 'S2'],
    chapterId: 'ch1',
    position: { x: 400, y: 560 },
  },

  // ======================================================================
  // 2. DATA PROTECTION LAW AND PRACTICE
  // ======================================================================
  {
    id: 'personal-data',
    slug: 'personal-data',
    title: 'Personal Data & Identifiability',
    clusterId: 'gdpr-data-governance',
    conciseDefinition: 'Under GDPR, information relating to an identified or identifiable living person, including names, online identifiers, and linkable pseudonyms.',
    expandedExplanation: 'The EU General Data Protection Regulation governs processing of personal data relating to identified or identifiable living persons, subject to its scope and exceptions. Names, email addresses, online identifiers, and linkable pseudonyms can be personal data. Genuinely anonymous information falls outside the GDPR. "It is public" or "we removed names" does not automatically make data anonymous.',
    whyItMatters: 'Data science pipelines that remove names but leave high-dimensional features or online identifiers remain fully subject to GDPR requirements.',
    example: 'A dataset of taxi trips stripped of passenger names but retaining precise GPS coordinates and pickup times remains personal data due to linkability.',
    limitationsOrMisconceptions: 'Public availability does not render data anonymous or exempt from GDPR; nor does removing direct names automatically achieve legal anonymity.',
    keywords: ['personal data', 'identifiability', 'gdpr', 'online identifiers', 'scope'],
    sourceIds: ['S2'],
    chapterId: 'ch2',
    position: { x: 920, y: 100 },
  },
  {
    id: 'anonymity-vs-pseudonymity',
    slug: 'anonymity-vs-pseudonymity',
    title: 'Pseudonymized vs. Anonymous Data',
    clusterId: 'gdpr-data-governance',
    conciseDefinition: 'Pseudonymized data normally remains personal data subject to GDPR; genuinely anonymous information falls outside the GDPR.',
    expandedExplanation: 'Pseudonymization replaces direct identifiers with pseudonyms or keys, reducing risk while allowing re-identification with separate key data. Pseudonymized data normally remains personal data under GDPR. In contrast, genuinely anonymous data cannot be linked to any identifiable living person by any means reasonably likely to be used, and falls outside GDPR scope.',
    whyItMatters: 'Organizations cannot escape GDPR obligations (such as lawful basis, notice, or access rights) merely by pseudonymizing or hashing database records.',
    example: 'Replacing patient medical record numbers with random hashes is pseudonymization; the records remain personal data if the key or auxiliary tables exist.',
    limitationsOrMisconceptions: '"We removed names" does not automatically make data anonymous; pseudonymized data normally remains personal data.',
    keywords: ['pseudonymization', 'anonymization', 'recital 26', 'personal data', 're-identification'],
    sourceIds: ['S2'],
    chapterId: 'ch2',
    position: { x: 1180, y: 100 },
  },
  {
    id: 'gdpr-baseline-principles',
    slug: 'gdpr-baseline-principles',
    title: 'GDPR Baseline Principles (Article 5)',
    clusterId: 'gdpr-data-governance',
    conciseDefinition: 'Article 5 principles: lawfulness, fairness, transparency, purpose limitation, data minimization, accuracy, storage limitation, integrity/confidentiality, and accountability.',
    expandedExplanation: 'Article 5 sets the fundamental conditions for personal data processing. Data must be processed lawfully, fairly, and transparently; collected for specified, explicit, and legitimate purposes (purpose limitation); limited to what is necessary (data minimization); accurate; stored no longer than necessary (storage limitation); secured against unauthorized access (integrity and confidentiality); and the controller must demonstrate compliance (accountability).',
    whyItMatters: 'Machine learning projects cannot hoard training data indefinitely without defined purposes, violating purpose limitation and data minimization.',
    example: 'Retaining customer location logs indefinitely without an operational purpose violates storage limitation and data minimization principles.',
    limitationsOrMisconceptions: 'GDPR compliance cannot be proved solely by selecting a privacy-enhancing algorithm; organizational accountability and baseline principles must be met.',
    keywords: ['article 5', 'principles', 'data minimization', 'purpose limitation', 'accountability'],
    sourceIds: ['S2'],
    chapterId: 'ch2',
    position: { x: 920, y: 240 },
  },
  {
    id: 'legal-bases-article-6-9',
    slug: 'legal-bases-article-6-9',
    title: 'Legal Bases for Processing (Articles 6 & 9)',
    clusterId: 'gdpr-data-governance',
    conciseDefinition: 'Article 6 requires an applicable legal basis: consent is one possible basis, not default or universal. Special-category data additionally requires an Article 9 condition.',
    expandedExplanation: 'Processing personal data requires a valid Article 6 legal basis (such as consent, contract, legal obligation, vital interests, public task, or legitimate interests). Consent is not the universal default requirement. Processing special-category data (health, genetic, biometric, racial, political data) additionally requires an Article 9 condition unless another applicable regime governs.',
    whyItMatters: 'Prevents projects from assuming that user consent is the only or always-valid basis, particularly where power imbalances make genuine consent impossible.',
    example: 'Processing patient genetic or health data requires an Article 9 condition in addition to an Article 6 legal basis.',
    limitationsOrMisconceptions: 'Consent is one possible legal basis, not the default or universal requirement; applicable duties depend on purpose, actors, data, and jurisdiction.',
    keywords: ['legal basis', 'article 6', 'article 9', 'consent', 'special category'],
    sourceIds: ['S2'],
    chapterId: 'ch2',
    position: { x: 1180, y: 240 },
  },
  {
    id: 'informing-people-articles-12-14',
    slug: 'informing-people-articles-12-14',
    title: 'Informing People (Articles 12, 13 & 14)',
    clusterId: 'gdpr-data-governance',
    conciseDefinition: 'Article 12 requires concise, transparent, intelligible, easily accessible information in plain language. Articles 13 & 14 govern direct and indirect collection.',
    expandedExplanation: 'Article 12 mandates clear, plain language for all communications. Article 13 applies when personal data is obtained directly from the data subject; Article 14 applies when data is collected from elsewhere (indirect collection). Timing, duties, and statutory exceptions differ between the two settings.',
    whyItMatters: 'Data science models trained on secondary, scraped, or brokered data must satisfy Article 14 indirect notice obligations.',
    example: 'A company acquiring third-party consumer profiles must provide Article 14 notifications unless a statutory exception applies.',
    limitationsOrMisconceptions: 'Stating "information must be provided where data are collected" is incomplete: indirect collection (Article 14) also triggers notice duties.',
    keywords: ['article 12', 'article 13', 'article 14', 'transparency', 'notice', 'plain language'],
    sourceIds: ['S2'],
    chapterId: 'ch2',
    position: { x: 920, y: 380 },
  },
  {
    id: 'automated-decisions-article-22',
    slug: 'automated-decisions-article-22',
    title: 'Automated Decisions (Article 22 & 13–15)',
    clusterId: 'gdpr-data-governance',
    conciseDefinition: 'Articles 13(2)(f), 14(2)(g), and 15(1)(h) require meaningful information about the logic and consequences of decisions based solely on automated processing under Article 22.',
    expandedExplanation: 'Do not memorize "the GDPR creates an unconditional right to an explanation of every algorithm." Articles 13(2)(f), 14(2)(g), and 15(1)(h) require meaningful information about the logic involved and the significance and envisaged consequences of automated decision-making referred to in Article 22. Article 22 concerns decisions based SOLELY on automated processing, including profiling, that produce legal or similarly significant effects. A human rubber stamp is not necessarily meaningful human involvement; conversely, not every AI-assisted decision is solely automated. Other transparency duties can still apply outside Article 22.',
    whyItMatters: 'Clarifies the exact statutory scope of explanation duties under GDPR, avoiding both over-promising universal explanation rights and under-protecting against rubber-stamped automation.',
    example: 'An automated CV filtering algorithm that rejects job applicants without human evaluation produces significant effects under Article 22.',
    limitationsOrMisconceptions: 'GDPR does not create an unconditional right to an explanation of every algorithm. Article 22 applies specifically to solely automated decisions with legal or similarly significant effects.',
    keywords: ['article 22', 'article 15', 'automated decision', 'profiling', 'logic involved', 'rubber stamp'],
    sourceIds: ['S2'],
    chapterId: 'ch2',
    position: { x: 1180, y: 380 },
  },
  {
    id: 'cjeu-dun-and-bradstreet',
    slug: 'cjeu-dun-and-bradstreet',
    title: 'CJEU Dun & Bradstreet Austria Ruling',
    clusterId: 'gdpr-data-governance',
    conciseDefinition: 'The CJEU clarified that under Article 15(1)(h), controllers must explain the procedure and principles actually applied so a person can understand data use and challenge outcomes.',
    expandedExplanation: 'The CJEU’s 2025 Dun & Bradstreet Austria decision clarified that, for the case under Article 15(1)(h), a controller must explain the procedure and principles actually applied so a person can understand which personal data were used and how, and can challenge the outcome. Simply handing over an algorithm or an opaque formula is insufficient. Trade-secret claims require balancing; they do not automatically erase the access right.',
    whyItMatters: 'Establishes that commercial secrecy or opaque mathematical formulas cannot be used to deny individuals meaningful explanations of profiling decisions.',
    example: 'A credit scoring agency cannot satisfy Article 15(1)(h) by providing source code or a mathematical equation without explaining which personal data were used and how they influenced the score.',
    limitationsOrMisconceptions: 'Trade-secret claims do not automatically erase access rights; courts require balancing commercial interests against the data subject’s right to understand and challenge decisions.',
    keywords: ['dun & bradstreet', 'cjeu', 'article 15', 'meaningful explanation', 'trade secrets', 'challenge outcome'],
    sourceIds: ['S2', 'S3'],
    chapterId: 'ch2',
    position: { x: 920, y: 500 },
  },
  {
    id: 'engineering-governance-dpia',
    slug: 'engineering-governance-dpia',
    title: 'Engineering Governance & DPIA (Article 35)',
    clusterId: 'gdpr-data-governance',
    conciseDefinition: 'Engineering steps: map data, define basis, minimize collection, set retention and security, assess DPIA under Article 35, and protect raw data.',
    expandedExplanation: 'Before processing: define purpose and legal basis, map data and recipients, minimize collection, decide retention, set access controls and security, and assess whether a data-protection impact assessment (DPIA) is required under Article 35. Protect raw data even if you publish only privacy-preserving statistics. A model’s explanations, logs and outputs may themselves contain personal data. GDPR compliance cannot be proved solely by selecting a privacy-enhancing algorithm.',
    whyItMatters: 'Ensures that privacy engineering addresses data mapping, retention schedules, and raw data security rather than relying solely on mathematical algorithms.',
    example: 'Conducting a formal Article 35 DPIA prior to deploying large-scale automated facial recognition or patient profiling pipelines.',
    limitationsOrMisconceptions: 'GDPR compliance cannot be proved solely by selecting a privacy-enhancing algorithm; raw data security, access controls, and retention limits are independently mandatory.',
    keywords: ['dpia', 'article 35', 'engineering governance', 'raw data protection', 'data mapping'],
    sourceIds: ['S2', 'S4'],
    chapterId: 'ch2',
    position: { x: 1180, y: 500 },
  },
  {
    id: 'law-enforcement-caveat',
    slug: 'law-enforcement-caveat',
    title: 'Law Enforcement Regime (LED vs GDPR)',
    clusterId: 'gdpr-data-governance',
    conciseDefinition: 'Processing by competent authorities for criminal-law-enforcement purposes generally falls under the EU Law Enforcement Directive and national law, rather than ordinary GDPR.',
    expandedExplanation: 'For personal-data processing by competent authorities for prevention, investigation, detection or prosecution of crimes, the EU Law Enforcement Directive and implementing national law generally govern instead of the ordinary GDPR regime. Do not mechanically apply GDPR Article 22 to every policing example.',
    whyItMatters: 'Prevents legal errors from applying commercial GDPR standards to criminal justice and policing systems.',
    example: 'A police department processing biometric data for a criminal investigation operates under the Law Enforcement Directive, not standard GDPR Article 22.',
    limitationsOrMisconceptions: 'Do not mechanically apply GDPR Article 22 to policing examples; separate statutory regimes govern law enforcement authorities.',
    keywords: ['law enforcement directive', 'led', 'policing', 'competent authorities', 'statutory scope'],
    sourceIds: ['S2'],
    chapterId: 'ch2',
    position: { x: 1050, y: 620 },
  },

  // ======================================================================
  // 3. DIFFERENTIAL PRIVACY
  // ======================================================================
  {
    id: 'differential-privacy',
    slug: 'differential-privacy',
    title: 'Differential Privacy (DP)',
    clusterId: 'differential-privacy',
    conciseDefinition: 'A mathematical guarantee about a randomized mechanism M bounding output distribution changes when one person’s data is added, removed, or changed.',
    expandedExplanation: 'Differential privacy (DP) is a mathematical guarantee about a RANDOMIZED data-release or computation mechanism M. Its output distribution changes only within a specified bound when one protected person’s data are added, removed, or changed, according to the stated definition of neighboring datasets: P[M(D) in S] <= exp(epsilon) * P[M(D\') in S] + delta. For pure epsilon-DP, delta = 0. The inequality must hold in both directions through quantifying over ordered neighboring pairs. "Neighbor" must be specified: one record is not necessarily the same as all records from one person.',
    whyItMatters: 'Provides a provable mathematical bound on individual output disclosure from released statistics, independent of auxiliary background knowledge.',
    example: 'A platform reporting a noisy count of people cycling to work, calibrated so a single person’s participation changes the underlying count by at most one.',
    limitationsOrMisconceptions: 'DP limits the influence of participation on a release. It cannot promise no adverse real-world effects, prevent group conclusions, erase background inferences, or secure raw data.',
    keywords: ['differential privacy', 'randomized mechanism', 'epsilon', 'delta', 'neighboring datasets'],
    sourceIds: ['S4'],
    chapterId: 'ch3',
    position: { x: 1680, y: 140 },
  },
  {
    id: 'dp-limits-and-interpretation',
    slug: 'dp-limits-and-interpretation',
    title: 'DP Interpretation & Limits',
    clusterId: 'differential-privacy',
    conciseDefinition: 'DP bounds incremental disclosure from a release; it does not promise no adverse real-world effect or secure raw data.',
    expandedExplanation: 'DP cannot promise that joining a study will never harm someone. If a study discovers that smoking causes lung cancer, a smoker’s insurance rates may rise regardless of their participation. DP bounds the incremental effect of one person’s participation on the distribution of a RELEASE; it cannot prevent conclusions about a whole group, stop inferences already possible from other information, or secure raw data during collection and storage. Auxiliary information does not invalidate the mathematical bound, but background facts can still support sensitive inferences.',
    whyItMatters: 'Prevents false promises to research subjects and ensures engineers do not mistake output perturbation for raw-data database protection.',
    example: 'A scientific study using DP discovers a link between an environmental exposure and a disease; everyone living in that area may experience insurance rate increases.',
    limitationsOrMisconceptions: 'DP does not guarantee that participation cannot harm someone, nor does it prevent aggregate group conclusions.',
    keywords: ['dp limits', 'incremental effect', 'group inference', 'auxiliary information', 'harm'],
    sourceIds: ['S4'],
    chapterId: 'ch3',
    position: { x: 1940, y: 140 },
  },
  {
    id: 'epsilon-and-delta',
    slug: 'epsilon-and-delta',
    title: 'Epsilon (ε) and Delta (δ) Parameters',
    clusterId: 'differential-privacy',
    conciseDefinition: 'Epsilon is the privacy-loss parameter (smaller ε = stronger privacy at cost to accuracy); Delta is an additional relaxation requiring explicit justification.',
    expandedExplanation: 'Epsilon (ε) is the privacy-loss parameter; for otherwise comparable mechanisms, smaller epsilon is stronger privacy, usually at a cost to accuracy. Delta (δ) is an additional relaxation; its choice and meaning need explicit justification. In pure DP, δ = 0.',
    whyItMatters: 'Calibrating ε and δ balances mathematical confidentiality against analytical utility for downstream data consumers.',
    example: 'For a fixed count query and noise mechanism, lowering epsilon generally requires more noise. The useful accuracy also depends on the count, sensitivity, and number of releases.',
    limitationsOrMisconceptions: 'An epsilon value alone does not establish adequate protection. Check delta, the protected unit, composition, implementation, and the trust model.',
    keywords: ['epsilon', 'delta', 'privacy loss', 'relaxation', 'accuracy trade-off'],
    sourceIds: ['S4'],
    chapterId: 'ch3',
    position: { x: 1680, y: 280 },
  },
  {
    id: 'composition-and-sensitivity',
    slug: 'composition-and-sensitivity',
    title: 'Sensitivity & Budget Composition',
    clusterId: 'differential-privacy',
    conciseDefinition: 'Sensitivity bounds how much one person can change a query; multiple releases cumulatively consume a shared privacy budget.',
    expandedExplanation: 'Sensitivity and contribution bounding limit how much a protected person’s data can change a query, then calibrate randomization accordingly. Unit of protection matters: event-level versus person-level privacy can yield very different real protection. Composition dictates that multiple releases consume a combined privacy budget; do not assess each dashboard or query in isolation.',
    whyItMatters: 'Repeated queries on the same dataset degrade privacy over time unless cumulative privacy loss is tracked and bounded.',
    example: 'An analyst executing multiple independent statistical queries against a customer database consumes a cumulative privacy budget under composition.',
    limitationsOrMisconceptions: 'Do not assess each query in isolation; multiple DP releases cumulatively deplete the privacy budget.',
    keywords: ['sensitivity', 'composition', 'privacy budget', 'unit of protection', 'contribution bounding'],
    sourceIds: ['S4'],
    chapterId: 'ch3',
    position: { x: 1940, y: 280 },
  },
  {
    id: 'central-vs-local-dp',
    slug: 'central-vs-local-dp',
    title: 'Central vs. Local Differential Privacy',
    clusterId: 'differential-privacy',
    conciseDefinition: 'Central DP protects released outputs from a trusted holder; Local DP randomizes before the holder sees the data, with different utility trade-offs.',
    expandedExplanation: 'Central DP randomizes outputs at a trusted data holder. Local DP randomizes each contribution before the holder sees it, reducing the need to trust the holder with raw values. Local approaches often need more data to reach comparable accuracy. Devices, implementations, and any metadata still require appropriate safeguards.',
    whyItMatters: 'Determines system architecture and trust requirements for client telemetry and centralized data repositories.',
    example: 'Local DP used in mobile operating system telemetry to gather keystroke frequencies without storing raw user inputs.',
    limitationsOrMisconceptions: 'Local DP requires substantial utility trade-offs and significantly larger user populations than Central DP.',
    keywords: ['central dp', 'local dp', 'trust model', 'utility trade-off', 'randomization'],
    sourceIds: ['S4'],
    chapterId: 'ch3',
    position: { x: 1680, y: 420 },
  },
  {
    id: 'raw-data-security',
    slug: 'raw-data-security',
    title: 'Raw-Data Security & DP',
    clusterId: 'differential-privacy',
    conciseDefinition: 'DP limits disclosure from released statistics; it does not replace raw-data security during collection and storage.',
    expandedExplanation: 'A properly calibrated DP release limits what a published output reveals about whether a person participated. It does not protect raw data logs if the database is leaked, breached, or improperly accessed. Furthermore, DP can reduce individual disclosure risk but can add statistical error that affects small groups differently. "DP-compliant" is not synonymous with "GDPR-compliant."',
    whyItMatters: 'Deploying differential privacy algorithms does not relieve an organization of securing backend servers, enforcing access controls, and minimizing retention.',
    example: 'A platform publishes DP-compliant transit statistics, but leaves its raw trip logs unencrypted on a vulnerable server.',
    limitationsOrMisconceptions: 'Differential privacy does not replace raw-data security; "DP-compliant" is not synonymous with "GDPR-compliant."',
    keywords: ['raw data security', 'breach', 'access control', 'gdpr compliance', 'subgroup error'],
    sourceIds: ['S2', 'S4'],
    chapterId: 'ch3',
    position: { x: 1940, y: 420 },
  },

  // ======================================================================
  // 4. EXPLANATION, TRANSPARENCY AND ACCOUNTABILITY
  // ======================================================================
  {
    id: 'transparency',
    slug: 'transparency',
    title: 'Transparency',
    clusterId: 'transparency-explanation',
    conciseDefinition: 'Meaningful openness about relevant processes, actors, purposes, data, limitations and decisions.',
    expandedExplanation: 'Transparency requires meaningful openness regarding the system’s purposes, data provenance, operating parameters, and limitations. It does not mean publishing every source-code line or all confidential personal data.',
    whyItMatters: 'Enables external auditors and affected individuals to understand system purposes and verify basic constraints.',
    example: 'Documenting training data demographics, intended operational use cases, and known limitations in model documentation.',
    limitationsOrMisconceptions: 'Transparency does not mean publishing every source-code line; nor does transparency automatically imply fairness or justifiability.',
    keywords: ['transparency', 'openness', 'documentation', 'limitations', 'data provenance'],
    sourceIds: ['S5'],
    chapterId: 'ch4',
    position: { x: 1680, y: 800 },
  },
  {
    id: 'interpretability',
    slug: 'interpretability',
    title: 'Interpretability',
    clusterId: 'transparency-explanation',
    conciseDefinition: 'The degree to which people can understand a model’s behavior or internal relationships.',
    expandedExplanation: 'Interpretability varies by audience and method; a simple model is not automatically an adequate explanation of a particular decision. Furthermore, "more complex = more accurate and less interpretable" is not a universal rule.',
    whyItMatters: 'Inherently interpretable models allow human operators to inspect decision logic directly without relying on post-hoc approximations.',
    example: 'Using a sparse linear model or shallow decision tree where domain experts can directly examine feature weights.',
    limitationsOrMisconceptions: 'A simple model is not automatically an adequate explanation of a particular decision; context and audience matter.',
    keywords: ['interpretability', 'model behavior', 'internal relationships', 'glass box'],
    sourceIds: ['S5'],
    chapterId: 'ch4',
    position: { x: 1940, y: 800 },
  },
  {
    id: 'explainability',
    slug: 'explainability',
    title: 'Explainability',
    clusterId: 'transparency-explanation',
    conciseDefinition: 'Ability to provide understandable, faithful reasons or evidence about a model’s output or decision-making process.',
    expandedExplanation: 'Explainability provides understandable, faithful reasons or evidence about a model’s output or decision-making process. Local feature attribution, a counterfactual example, and a clinical rationale answer different questions. Post-hoc explanations may be approximate rather than faithful to the model’s true decision process.',
    whyItMatters: 'Allows affected individuals to understand why a specific adverse decision was rendered and what inputs can be contested.',
    example: 'Providing a counterfactual explanation showing what specific change in an applicant’s financial history would alter a credit decision.',
    limitationsOrMisconceptions: 'Post-hoc explanations may be approximate rather than faithful to the model’s true decision process.',
    keywords: ['explainability', 'faithful reasons', 'counterfactual', 'feature attribution', 'post-hoc'],
    sourceIds: ['S5'],
    chapterId: 'ch4',
    position: { x: 1680, y: 940 },
  },
  {
    id: 'justifiability',
    slug: 'justifiability',
    title: 'Justifiability',
    clusterId: 'transparency-explanation',
    conciseDefinition: 'Whether the system’s design, deployment, purposes, procedures, and outcomes can be defended on ethical, legal, and empirical grounds.',
    expandedExplanation: 'Justifiability evaluates whether an algorithmic system ought to exist and operate in a given domain. Explaining an unjustified decision does not justify it. A system can be fully transparent and accurately explained while remaining ethically indefensible or unlawful.',
    whyItMatters: 'Prevents data scientists from assuming that making an algorithm transparent or explainable makes it ethically acceptable.',
    example: 'An automated biometric surveillance system that is fully documented and transparent, yet lacks statutory authority or ethical justification.',
    limitationsOrMisconceptions: 'Explaining an unjustified decision does not justify it. Transparency does not automatically imply fairness or justifiability.',
    keywords: ['justifiability', 'ethical defense', 'legal grounds', 'empirical defense', 'legitimacy'],
    sourceIds: ['S5'],
    chapterId: 'ch4',
    position: { x: 1940, y: 940 },
  },
  {
    id: 'epistemic-accessibility',
    slug: 'epistemic-accessibility',
    title: 'Epistemic Accessibility & Black Boxes',
    clusterId: 'transparency-explanation',
    conciseDefinition: 'How readily relevant knowledge can be obtained and understood. A black box is a system whose relevant workings are inaccessible or difficult to inspect.',
    expandedExplanation: 'Epistemic accessibility concerns how readily and fully relevant knowledge can be obtained and understood: documentation, independent assessment, uncertainty, and contestability all matter. A black box is a system whose relevant internal workings are inaccessible or difficult for a given observer to inspect or understand. It is not necessarily literally impossible for every human to inspect. Complexity, secrecy, and missing documentation are different causes of opacity.',
    whyItMatters: 'Enables operators to verify inputs and detect drift, and gives auditors the ability to reconstruct data provenance and human interventions.',
    example: 'Auditing a credit scoring system by inspecting data provenance, training thresholds, and operator override logs.',
    limitationsOrMisconceptions: 'Black-box opacity is not always caused by mathematical complexity; corporate secrecy and missing documentation are distinct causes.',
    keywords: ['epistemic accessibility', 'black box', 'opacity', 'auditability', 'contestability'],
    sourceIds: ['S3', 'S5'],
    chapterId: 'ch4',
    position: { x: 1680, y: 1080 },
  },
  {
    id: 'fat-fact-fast-acronyms',
    slug: 'fat-fact-fast-acronyms',
    title: 'FAT, FACT and FAST Acronyms',
    clusterId: 'transparency-explanation',
    conciseDefinition: 'Course acronyms (FAT, FACT, FAST) are memorable teaching aids, not one universal or exhaustive standard.',
    expandedExplanation: 'FAT (fairness, accountability, transparency), FACT (fairness, accuracy, confidentiality, transparency), and FAST (fairness, accountability, sustainability, transparency) are memorable course acronyms, not one universal or exhaustive standard. Accuracy, confidentiality, security, privacy, robustness, accessibility, recourse, and institutional responsibility should not disappear just because an acronym omits them. Also distinguish confidentiality (restricting unauthorized access) from privacy (appropriate treatment of people and their data).',
    whyItMatters: 'Reminds practitioners that vital safeguards like security, privacy, and recourse must not be omitted simply because an acronym leaves them out.',
    example: 'An engineering checklist ensuring data security and contestability are maintained even when following a basic "FAT" framework.',
    limitationsOrMisconceptions: 'FAT, FACT, and FAST are not exhaustive standards. Distinguish confidentiality from privacy.',
    keywords: ['fat', 'fact', 'fast', 'acronyms', 'confidentiality vs privacy', 'recourse'],
    sourceIds: ['S5'],
    chapterId: 'ch4',
    position: { x: 1940, y: 1080 },
  },

  // ======================================================================
  // 5. RESPONSIBILITY, FORESEEABILITY AND DUAL USE
  // ======================================================================
  {
    id: 'forward-looking-responsibility',
    slug: 'forward-looking-responsibility',
    title: 'Forward-Looking Responsibility',
    clusterId: 'responsibility-dual-use',
    conciseDefinition: 'Duties to anticipate, prevent, monitor and respond to prospective outcomes.',
    expandedExplanation: 'Forward-looking responsibility concerns prospective duties: assessing foreseeable risks, monitoring model drift, red-teaming, and establishing safeguards before and during deployment. It contrasts with backward-looking responsibility, which assesses accountability after an event has occurred.',
    whyItMatters: 'Encourages proactive risk mitigation in data science rather than reacting only after harms materialize.',
    example: 'Establishing pre-deployment risk evaluations, staged rollouts, and continuous monitoring for diagnostic AI.',
    limitationsOrMisconceptions: 'Forward-looking responsibility does not require predicting every impossible contingency, but demands assessing reasonably foreseeable outcomes.',
    keywords: ['forward-looking', 'prospective duties', 'prevention', 'monitoring', 'risk assessment'],
    sourceIds: ['S5'],
    chapterId: 'ch5',
    position: { x: 920, y: 880 },
  },
  {
    id: 'backward-looking-responsibility',
    slug: 'backward-looking-responsibility',
    title: 'Backward-Looking Responsibility',
    clusterId: 'responsibility-dual-use',
    conciseDefinition: 'Assessment of responsibility for something that occurred, potentially including blame, liability, or answerability.',
    expandedExplanation: 'Backward-looking responsibility evaluates past harms. Blame, liability, and answerability are not interchangeable: an institution can have liability or answerability without an individual bearing moral blame. Legal liability follows applicable law, not just philosophical intuitions.',
    whyItMatters: 'Governs incident response, forensic auditing, and legal remediation when algorithms cause injury.',
    example: 'Investigating whether software deployers or hospital administrators bear liability following a diagnostic model failure.',
    limitationsOrMisconceptions: 'Blame, liability, and answerability are not interchangeable; legal liability follows statutory law rather than philosophical intuitions.',
    keywords: ['backward-looking', 'liability', 'blame', 'answerability', 'remediation'],
    sourceIds: ['S5'],
    chapterId: 'ch5',
    position: { x: 1200, y: 880 },
  },
  {
    id: 'active-vs-passive-responsibility',
    slug: 'active-vs-passive-responsibility',
    title: 'Active vs. Passive Responsibility',
    clusterId: 'responsibility-dual-use',
    conciseDefinition: 'Active responsibility is taking and exercising a role in securing an outcome or repairing harm; passive responsibility is being held to account by others.',
    expandedExplanation: 'Active responsibility involves taking an active role in securing a future outcome or proactively investigating and repairing past harm. Passive responsibility is being called to account by external authorities or affected parties. This is a conceptual distinction, not a rule that self-assessment is impossible.',
    whyItMatters: 'Distinguishes internal organizational stewardship from external regulatory compliance and liability.',
    example: 'An engineering team proactively auditing a recommender for feedback loops (active) versus answering a regulatory inquiry after consumer complaints (passive).',
    limitationsOrMisconceptions: 'This is a conceptual distinction, not a rule that self-assessment is impossible.',
    keywords: ['active responsibility', 'passive responsibility', 'accountability', 'stewardship'],
    sourceIds: ['S5'],
    chapterId: 'ch5',
    position: { x: 1060, y: 980 },
  },
  {
    id: 'conditions-for-moral-blame',
    slug: 'conditions-for-moral-blame',
    title: 'Conditions for Moral Blame',
    clusterId: 'responsibility-dual-use',
    conciseDefinition: 'Knowledge/foreseeability and control: What did the person know or ought to have known? What capacity did they have to prevent or alter the outcome?',
    expandedExplanation: 'Knowledge/foreseeability and control are central to many accounts of moral blame: What did the person know or reasonably ought to have known? What capacity did they have to prevent or alter the outcome? These are not complete universal formulas. Institutional responsibility to investigate and remedy harm can persist even where no individual’s blame is established.',
    whyItMatters: 'Clarifies that an organization retains responsibility to remedy algorithmic harm even when individual developers lacked full foreseeability or control.',
    example: 'A developer implementing a sub-component without knowledge of how the wider system would be deployed may lack individual moral blame, but the deploying institution remains responsible.',
    limitationsOrMisconceptions: 'These are not complete universal formulas; institutional responsibility to remedy harm persists even where no individual’s blame is established.',
    keywords: ['moral blame', 'foreseeability', 'control capacity', 'institutional duty'],
    sourceIds: ['S5'],
    chapterId: 'ch5',
    position: { x: 920, y: 1080 },
  },
  {
    id: 'dual-use-technology',
    slug: 'dual-use-technology',
    title: 'Dual-Use Potential',
    clusterId: 'responsibility-dual-use',
    conciseDefinition: 'A tool has dual-use potential if it can be used for beneficial and harmful purposes, sometimes beyond its intended application.',
    expandedExplanation: '"Dual use = unintended use" is too narrow: an anticipated use can still be dual use, and an unintended use need not be harmful. Reasonable foreseeability matters, but complexity makes prediction imperfect. Assess plausible misuse and affected parties, constrain capabilities and access proportionately, keep records of risks and mitigations, consult domain experts, and follow relevant reporting rules. Mere speculation must not automatically halt all research.',
    whyItMatters: 'Mandates practical risk governance for powerful data tools (such as generative models or protein analysis) without paralyzing scientific research.',
    example: 'Voice synthesis tools designed for accessibility assistance that can also be repurposed for unauthorized voice impersonation.',
    limitationsOrMisconceptions: '"Dual use = unintended use" is too narrow; an anticipated use can still be dual use, and unintended uses are not necessarily harmful.',
    keywords: ['dual use', 'foreseeability', 'misuse', 'capability constraints', 'proportionality'],
    sourceIds: ['S5'],
    chapterId: 'ch5',
    position: { x: 1200, y: 1080 },
  },
  {
    id: 'precaution-and-dilemma-of-control',
    slug: 'precaution-and-dilemma-of-control',
    title: 'Precaution & The Dilemma of Control',
    clusterId: 'responsibility-dual-use',
    conciseDefinition: 'The dilemma of control: early on, changes are easier but effects harder to predict; later, evidence improves but entrenched deployments are harder to change.',
    expandedExplanation: 'A very strong precautionary rule ("do nothing unless absolute safety is certain") is generally impossible to satisfy; a moderate approach compares plausible benefits, harms, uncertainty and reversibility. Potentially severe irreversible harms justify extra caution. The dilemma of control: early in a technology’s life, changes are easier but effects harder to predict; later, evidence improves but entrenched deployments are harder to change. Prefer reversible pilots, monitoring, staged rollout and pre-set stop conditions.',
    whyItMatters: 'Guides deployment strategies away from irreversible entrenchment toward staged, reversible pilots with defined stop rules.',
    example: 'Deploying an automated triage algorithm in a reversible clinical pilot with pre-set stop conditions rather than immediately entrenching it hospital-wide.',
    limitationsOrMisconceptions: 'Strong precaution ("do nothing unless safety is certain") is impossible to satisfy; moderate precaution balances benefits, harms, uncertainty, and reversibility.',
    keywords: ['dilemma of control', 'precaution', 'reversibility', 'staged rollout', 'stop conditions'],
    sourceIds: ['S5'],
    chapterId: 'ch5',
    position: { x: 920, y: 1200 },
  },
  {
    id: 'problem-of-many-hands',
    slug: 'problem-of-many-hands',
    title: 'The Problem of Many Hands',
    clusterId: 'responsibility-dual-use',
    conciseDefinition: 'A harmful outcome can emerge from interactions among collectors, labelers, developers, managers, vendors, and deployers without a single culprit.',
    expandedExplanation: 'Lack of a single obvious culprit does not imply that nobody has duties. Allocate decision rights and responsibilities in advance; retain traceable records; specify who can stop deployment, handle complaints, investigate incidents and compensate affected people. Assigning responsibility purely in proportion to code contribution is often inadequate because authority and control differ. Collective responsibility can supplement, not replace, individual and organizational accountability.',
    whyItMatters: 'Prevents organizational diffusion of responsibility where every contributor points to another team member or third-party vendor.',
    example: 'A biased recruiting tool created by vendor data, labeled by contractors, tuned by developers, and deployed by HR without clear override authority.',
    limitationsOrMisconceptions: 'Lack of a single obvious culprit does not imply nobody has duties; assigning responsibility purely by code contribution is inadequate.',
    keywords: ['problem of many hands', 'collective responsibility', 'decision rights', 'traceable records', 'accountability'],
    sourceIds: ['S5'],
    chapterId: 'ch5',
    position: { x: 1200, y: 1200 },
  },

  // ======================================================================
  // 6. BIAS, FAIRNESS AND JUSTICE
  // ======================================================================
  {
    id: 'statistical-vs-social-bias',
    slug: 'statistical-vs-social-bias',
    title: 'Statistical vs. Social Bias',
    clusterId: 'bias-measurement',
    conciseDefinition: 'Statistical bias is systematic estimation error; social bias refers to patterns of disadvantage. The two can interact but are not identical.',
    expandedExplanation: 'Distinguish statistical bias (systematic estimation error) from social or discriminatory bias (patterns of disadvantage); the two can interact but are not identical. NIST groups AI bias into systemic, computational/statistical, and human-cognitive sources. Unfair outcomes do not require discriminatory intent.',
    whyItMatters: 'A model can have zero statistical estimation error relative to historical records while automating and entrenching severe social discrimination.',
    example: 'An algorithm accurately estimating historical arrest rates mirrors the statistical data, but reflects social bias from historical over-policing.',
    limitationsOrMisconceptions: 'Eliminating statistical bias does not eliminate social bias; unfair outcomes do not require discriminatory intent.',
    keywords: ['statistical bias', 'social bias', 'systemic bias', 'nist taxonomy', 'estimation error'],
    sourceIds: ['S5', 'S7'],
    chapterId: 'ch6',
    position: { x: 180, y: 840 },
  },
  {
    id: 'sampling-selection-bias',
    slug: 'sampling-selection-bias',
    title: 'Sampling / Selection Bias',
    clusterId: 'bias-measurement',
    conciseDefinition: 'A dataset differs systematically from the target population because inclusion or observation is uneven.',
    expandedExplanation: 'A dataset may differ systematically from the target population because inclusion or observation is uneven. Merely having different group counts is not automatically proof of unfairness; assess what population and estimand are intended.',
    whyItMatters: 'Leads to degraded model performance on underrepresented groups when the training sample diverges from the operating population.',
    example: 'A health app trained only on smartphone owners failing when deployed across a broader population that includes elderly non-smartphone users.',
    limitationsOrMisconceptions: 'Merely having different numerical group counts in a dataset is not automatically proof of unfairness; target population and estimand must be evaluated.',
    keywords: ['sampling bias', 'selection bias', 'target population', 'estimand', 'uneven observation'],
    sourceIds: ['S5'],
    chapterId: 'ch6',
    position: { x: 420, y: 840 },
  },
  {
    id: 'label-measurement-bias',
    slug: 'label-measurement-bias',
    title: 'Label / Measurement Bias',
    clusterId: 'bias-measurement',
    conciseDefinition: 'The measured outcome differs from the outcome of interest, potentially in group-specific ways.',
    expandedExplanation: 'Label or measurement bias occurs when the recorded variable differs from the true construct of interest. For example: recorded arrests are not the same thing as all crimes committed; policing practices affect who is recorded.',
    whyItMatters: 'When the proxy label reflects institutional enforcement disparities rather than true behavior, models optimize for the flawed proxy.',
    example: 'Using recorded police arrests as a proxy for actual crime occurrences, when arrest rates reflect patrol intensity.',
    limitationsOrMisconceptions: 'Recorded data does not automatically equal the underlying construct of interest; proxy variables must be critically examined.',
    keywords: ['label bias', 'measurement bias', 'recorded arrests', 'proxy variable', 'construct validity'],
    sourceIds: ['S5', 'S8'],
    chapterId: 'ch6',
    position: { x: 180, y: 1000 },
  },
  {
    id: 'algorithmic-optimization-bias',
    slug: 'algorithmic-optimization-bias',
    title: 'Algorithmic / Optimization Bias',
    clusterId: 'bias-measurement',
    conciseDefinition: 'Choices of target, features, loss, threshold, evaluation, or deployment can create or amplify inequity, even with balanced data.',
    expandedExplanation: 'Algorithmic or optimization bias arises from choices in target definition, feature selection, loss weighting, classification thresholds, or evaluation criteria. Even on an apparently balanced dataset, these engineering choices can create or amplify disparate error rates.',
    whyItMatters: 'Demonstrates that fairness issues cannot be resolved solely by cleaning datasets; the mathematical objective function and threshold choices directly impact equity.',
    example: 'Minimizing average global loss across a dataset, causing the model to optimize heavily for the majority group while accepting high errors on minorities.',
    limitationsOrMisconceptions: 'Balanced training data does not guarantee unbiased outputs; loss functions and thresholding choices can independently generate inequity.',
    keywords: ['optimization bias', 'loss function', 'thresholding', 'target definition', 'feature selection'],
    sourceIds: ['S5', 'S7'],
    chapterId: 'ch6',
    position: { x: 420, y: 1000 },
  },
  {
    id: 'interaction-bias-and-feedback-loops',
    slug: 'interaction-bias-and-feedback-loops',
    title: 'Interaction Bias & Filter Bubbles',
    clusterId: 'bias-measurement',
    conciseDefinition: 'Users can shape system outputs, and outputs can shape the data collected next. Personalization may also narrow what people encounter.',
    expandedExplanation: 'Interaction bias can arise when user behavior and feedback reshape outputs. Filter bubbles concern narrowed exposure to information; feedback loops occur when outputs influence future inputs. These mechanisms can overlap, but are not identical or inevitable. The Tay chatbot illustrates user manipulation, not a definition of every feedback loop.',
    whyItMatters: 'A deployed system changes the setting in which new data are collected. Evaluation needs to account for this interaction over time.',
    example: 'The Tay chatbot absorbing inflammatory language from public user interactions over time.',
    limitationsOrMisconceptions: 'Use "filter bubble" or "feedback loop" rather than "emergent bias." It is not inevitable that every recommender shields people from all conflicting information.',
    keywords: ['interaction bias', 'filter bubbles', 'feedback loops', 'personalization', 'tay chatbot'],
    sourceIds: ['S5', 'S8'],
    chapterId: 'ch6',
    position: { x: 300, y: 1140 },
  },
  {
    id: 'normative-ideals',
    slug: 'normative-ideals',
    title: 'Normative Ideals (Equality, Equity, Justice)',
    clusterId: 'fairness-justice',
    conciseDefinition: 'Equality: equal treatment/resources. Equity: adapted to circumstances to reduce disadvantage. Justice: evaluates institutions and root causes.',
    expandedExplanation: 'Equality usually means applying the same rule or distributing the same resources. Equity adapts support to different circumstances to reduce unjust disadvantage. Justice also examines institutions and the causes of disadvantage. Merit rewards selected contributions or achievements, but unequal opportunity can shape those achievements. Need prioritizes unmet needs; it does not by itself determine who should pay. These principles need interpretation in each setting.',
    whyItMatters: 'Prevents data scientists from treating equality, equity, and justice as interchangeable buzzwords with identical technical implementations.',
    example: 'Providing the exact same educational software to all students is equality; adapting instruction to learning differences is equity; restructuring underfunded school districts addresses justice.',
    limitationsOrMisconceptions: 'These are distinct normative concepts, not interchangeable formulas. "Reality" is a teaching illustration, not a technical category.',
    keywords: ['equality', 'equity', 'justice', 'merit', 'need', 'normative ideals'],
    sourceIds: ['S6', 'S7'],
    chapterId: 'ch6',
    position: { x: 200, y: 1540 },
  },
  {
    id: 'rawls-justice-as-fairness',
    slug: 'rawls-justice-as-fairness',
    title: 'Rawls: Justice as Fairness',
    clusterId: 'fairness-justice',
    conciseDefinition: 'Equal basic liberties, fair equality of opportunity, and inequalities arranged to the greatest benefit of the least advantaged, in that priority order.',
    expandedExplanation: 'Rawls protects equal basic liberties and fair equality of opportunity. The difference principle permits social and economic inequalities only if they are to the greatest benefit of the least advantaged, subject to the priority of the other principles. It is not a rule for maximizing total welfare. A useful critique asks how well the framework addresses particular histories of oppression and relational inequality.',
    whyItMatters: 'Provides an established ethical test against sacrificing fundamental rights or vulnerable populations to maximize aggregate efficiency.',
    example: 'An automated administrative system that increases total municipal savings but drastically worsens outcomes for low-income residents fails Rawlsian justice.',
    limitationsOrMisconceptions: 'Rawls’s difference principle cannot be reduced to total welfare maximization; principles are lexically ordered, and basic liberties take priority.',
    keywords: ['rawls', 'justice as fairness', 'difference principle', 'basic liberties', 'ordered principles'],
    sourceIds: ['S6'],
    chapterId: 'ch6',
    position: { x: 440, y: 1540 },
  },
  {
    id: 'group-and-individual-fairness',
    slug: 'group-and-individual-fairness',
    title: 'Group and Individual Fairness',
    clusterId: 'fairness-justice',
    conciseDefinition: 'Group fairness compares outcomes/errors across groups (demographic parity, equalized odds). Individual fairness requires similar treatment for similar individuals.',
    expandedExplanation: 'Group fairness compares outcomes or errors across defined groups. Demographic parity, for example, compares positive decision rates; equalized odds compares true-positive AND false-positive rates conditioned on the true outcome. Individual fairness asks whether individuals similar in morally relevant respects are treated similarly; it requires a defensible notion of similarity, and historical disadvantages may contaminate apparently neutral features. No one metric proves justice.',
    whyItMatters: 'Demonstrates the practical trade-offs between demographic parity, equalized odds, and individual similarity metrics.',
    example: 'Checking whether a hiring filter selects equal proportions of male and female candidates (demographic parity) versus equal true positive rates (equalized opportunity).',
    limitationsOrMisconceptions: 'No single metric establishes justice; individual fairness requires a defensible similarity metric which may itself be contaminated by historical disadvantage.',
    keywords: ['group fairness', 'individual fairness', 'demographic parity', 'equalized odds', 'similarity metric'],
    sourceIds: ['S7'],
    chapterId: 'ch6',
    position: { x: 200, y: 1680 },
  },
  {
    id: 'fairness-impossibility',
    slug: 'fairness-impossibility',
    title: 'Fairness Metric Incompatibility',
    clusterId: 'fairness-justice',
    conciseDefinition: 'With different group outcome rates, certain combinations of calibration, predictive parity, and equalized odds generally conflict for imperfect predictors.',
    expandedExplanation: 'When underlying outcome rates differ across groups, an imperfect predictor generally cannot satisfy certain combinations of calibration/predictive parity and equalized odds at once. Select and justify metrics based on the harms, use case, and affected people, not by dashboard convenience.',
    whyItMatters: 'Proves mathematically that algorithmic fairness cannot be reduced to satisfying all statistical metrics at once; explicit normative priorities must be justified.',
    example: 'With different outcome rates across groups, a non-degenerate imperfect binary classifier generally cannot have both predictive parity and equal true-positive and false-positive rates. Which condition to prioritize depends on the harm being addressed.',
    limitationsOrMisconceptions: 'No single fairness metric establishes justice; mathematical trade-offs cannot be solved by dashboard convenience.',
    keywords: ['incompatibility', 'calibration', 'equalized odds', 'base rates', 'trade-offs'],
    sourceIds: ['S7'],
    chapterId: 'ch6',
    position: { x: 440, y: 1680 },
  },
  {
    id: 'five-sociotechnical-traps',
    slug: 'five-sociotechnical-traps',
    title: 'The Five Sociotechnical Traps',
    clusterId: 'fairness-justice',
    conciseDefinition: 'Failure modes from Selbst et al. (2019): Framing, Portability, Formalism, Ripple-effect, and Solutionism traps.',
    expandedExplanation: 'The names describe failure modes in Selbst et al., "Fairness and Abstraction in Sociotechnical Systems" (2019): 1. Framing trap: model/data boundaries leave out relevant human actors, institutions and impacts. 2. Portability trap: a solution validated in one setting is moved to another without its local social and technical conditions. 3. Formalism trap: a mathematical fairness definition is mistaken for the full procedural, contextual and contested social concept. 4. Ripple-effect trap: introducing a system changes behavior, incentives and even the distribution of the problem it was built to solve. 5. Solutionism trap: presuming a technical tool is needed when the best intervention may be policy, staffing, service design or not deploying. The constructive goal is a fairer PROCESS for defining the problem, involving affected people, evaluating interventions and monitoring real outcomes, not merely a "fair" model score.',
    whyItMatters: 'Essential failure modes explaining why technically compliant algorithms produce disastrous real-world social impacts.',
    example: 'An apparently unbiased hiring screener can still disadvantage applicants if the job advert reaches one group less often, interviewers override scores unequally, or disability accommodations are inaccessible.',
    limitationsOrMisconceptions: 'The five traps are failure modes to diagnose and avoid, not the remedies themselves.',
    keywords: ['framing trap', 'portability trap', 'formalism trap', 'ripple-effect trap', 'solutionism trap', 'selbst'],
    sourceIds: ['S8'],
    chapterId: 'ch6',
    position: { x: 320, y: 1820 },
  },

  // ======================================================================
  // 7. HIGH-STAKES APPLICATIONS
  // ======================================================================
  {
    id: 'precision-and-predictive-medicine',
    slug: 'precision-and-predictive-medicine',
    title: 'Precision & Predictive Medicine',
    clusterId: 'high-stakes-applications',
    conciseDefinition: 'Precision medicine guides prevention, diagnosis, and treatment using multi-modal data. Predictive medicine estimates risk to support earlier intervention.',
    expandedExplanation: 'Precision medicine uses genomic, environmental and lifestyle information, among other relevant clinical information, to guide prevention, diagnosis and treatment. It does not mean each patient receives a wholly unique therapy. Predictive medicine may estimate risk or likely response and support earlier intervention; a model estimates uncertain outcomes, not a definite individual future. Assessment needs external validation, calibration, subgroup performance, clinical utility, consent or another suitable legal basis, and harm from false positives/negatives.',
    whyItMatters: 'Medical algorithms must be evaluated on real clinical utility and subgroup performance rather than general accuracy metrics alone.',
    example: 'A cardiovascular risk model used to stratify patients for preventive statin therapy, requiring external validation across diverse patient cohorts.',
    limitationsOrMisconceptions: 'Precision medicine does not mean each patient receives a wholly unique therapy; predictive models estimate uncertain probabilities, not definite individual futures.',
    keywords: ['precision medicine', 'predictive medicine', 'clinical utility', 'external validation', 'subgroup performance'],
    sourceIds: ['S9', 'S10'],
    chapterId: 'ch7',
    position: { x: 1080, y: 1540 },
  },
  {
    id: 'biomedical-ethics-principles',
    slug: 'biomedical-ethics-principles',
    title: 'Four Biomedical Ethics Principles',
    clusterId: 'high-stakes-applications',
    conciseDefinition: 'Autonomy (informed choices), Beneficence (patient benefit), Non-maleficence (minimize harm/negligence), Justice (fair access/burden sharing).',
    expandedExplanation: 'Autonomy: support informed choices and respect patients’ preferences; consent rules depend on intervention and law. Beneficence: act for the patient’s benefit. Non-maleficence: avoid and minimize harm, including negligent and foreseeable harm; not merely "do not intentionally injure." Justice: fair access, burden sharing, and attention to unmet need. These principles can conflict and do not substitute for clinical evidence, professional obligations or law. WHO separately identifies principles for AI in health including human autonomy, safety and well-being, intelligibility, accountability, inclusiveness and sustainability.',
    whyItMatters: 'Provides the standard bioethical framework to evaluate healthcare algorithms and clinical decision aids.',
    example: 'Balancing non-maleficence and autonomy when determining whether patients must be informed of experimental predictive risk scores.',
    limitationsOrMisconceptions: 'Principles can conflict and do not substitute for clinical evidence or law; non-maleficence extends beyond intentional injury to foreseeable and negligent harm.',
    keywords: ['autonomy', 'beneficence', 'non-maleficence', 'justice', 'biomedical ethics', 'who principles'],
    sourceIds: ['S10'],
    chapterId: 'ch7',
    position: { x: 1380, y: 1540 },
  },
  {
    id: 'clinical-trust-and-explainability',
    slug: 'clinical-trust-and-explainability',
    title: 'Clinical Trust & Social Epistemology',
    clusterId: 'high-stakes-applications',
    conciseDefinition: 'AI systems are not professional peers. "Algorithms can’t give evidence" is false, but a confidence score alone is not a clinical explanation.',
    expandedExplanation: 'Social epistemology studies knowledge and justification in social contexts: expertise, testimony, institutions and trust. Patients may reasonably rely on clinicians’ expertise while still needing information in a form they can use to consent or decline. Clinical trust is earned through competence, evidence, communication and accountability, not blind deference. AI systems are not human professional peers in the full sense of holding professional obligations or deliberating as persons. But "algorithms can’t give evidence" is false: models can be evaluated on data, provide calibrated predictions and sometimes supply interpretable rationales. A confidence score alone is not a clinical explanation. A clinician’s nominal final authority is insufficient if they cannot understand, question, override or safely ignore a tool. Responsibility should be distributed explicitly among developers, healthcare organizations, deployers and clinicians rather than assigned automatically to whichever doctor clicked "accept."',
    whyItMatters: 'Prevents healthcare organizations from using frontline clinicians as nominal liability buffers for broken AI tools.',
    example: 'An AI diagnostic tool displaying a 91% confidence score without clinical rationales or input verification capabilities.',
    limitationsOrMisconceptions: 'Algorithms can give evidence; but a confidence score alone is not a clinical explanation, and nominal final authority is insufficient if clinicians cannot question or safely ignore a tool.',
    keywords: ['clinical trust', 'social epistemology', 'algorithmic evidence', 'confidence score', 'distributed responsibility'],
    sourceIds: ['S10'],
    chapterId: 'ch7',
    position: { x: 1080, y: 1720 },
  },
  {
    id: 'predictive-policing',
    slug: 'predictive-policing',
    title: 'Predictive Policing & Feedback Loops',
    clusterId: 'high-stakes-applications',
    conciseDefinition: 'Applies statistical techniques to forecast crime events, locations, or persons. Risks include feedback loops in recorded crime, discriminatory surveillance, and diffusion of responsibility.',
    expandedExplanation: 'Predictive policing applies statistical techniques to forecast possible crime-related events, locations or persons, depending on the system. Claimed benefits include directing limited resources and revealing patterns; these are hypotheses to validate against suitable baselines, not automatic outcomes. Risks include feedback loops in recorded crime, discriminatory surveillance, false accusations, privacy harms, weak transparency, and diffusion of responsibility. A tool may reduce some discretionary human errors and simultaneously encode historical bias.',
    whyItMatters: 'Illustrates how statistical models trained on recorded enforcement data automate historical bias and generate self-reinforcing cycles.',
    example: 'Patrolling a neighborhood based on past drug arrest records leads to more drug arrests in that area, reinforcing the algorithm’s initial prediction.',
    limitationsOrMisconceptions: 'Claimed benefits are hypotheses to validate against baselines, not automatic outcomes; tools may reduce some human errors while encoding historical bias.',
    keywords: ['predictive policing', 'feedback loops', 'recorded crime', 'discriminatory surveillance', 'diffusion of responsibility'],
    sourceIds: ['S5', 'S8'],
    chapterId: 'ch7',
    position: { x: 1380, y: 1720 },
  },
  {
    id: 'policing-oversight-and-ai-act',
    slug: 'policing-oversight-and-ai-act',
    title: 'Policing Oversight & EU AI Act',
    clusterId: 'high-stakes-applications',
    conciseDefinition: 'Before deployment ask: What target is predicted? Who is missing? What action follows? In the EU, the AI Act prohibits certain individual criminal risk assessments.',
    expandedExplanation: 'Before deployment, establish what is being predicted, who is missing from the data, what action follows a score, and how people can challenge it. The EU AI Act prohibits certain individual criminal-offence risk assessments based solely on profiling or personality traits. The provision excludes tools supporting a human assessment of involvement in criminal activity already based on objective and verifiable facts directly linked to that activity. Some other law-enforcement uses are high-risk. The rules depend on the system, purpose, and applicable dates. Oversight also needs training, access controls, incident review, and routes to challenge.',
    whyItMatters: 'Sets the statutory and procedural oversight questions mandatory before any law enforcement predictive tool can be deployed.',
    example: 'Evaluating whether predicting "recorded arrests" rather than "actual crime incidents" makes a proposed policing tool legally or procedurally flawed.',
    limitationsOrMisconceptions: 'An explainability widget is not sufficient oversight; lawful, necessary, and proportionate deployment requires independent routes to challenge and incident review.',
    keywords: ['eu ai act', 'policing oversight', 'prohibited ai', 'high risk', 'contestation', 'target variable'],
    sourceIds: ['S2', 'S8', 'S11'],
    chapterId: 'ch7',
    position: { x: 1230, y: 1860 },
  },
];
