import { Source } from './types';

export const sources: Source[] = [
  {
    id: 'S1',
    title: 'Privacy',
    authorOrInstitution: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/privacy/',
    contextualNote: 'Foundational philosophical treatment of privacy dimensions, access vs control accounts, contextual integrity, and the ethical values protected by privacy boundaries.',
  },
  {
    id: 'S2',
    title: 'Regulation (EU) 2016/679 (General Data Protection Regulation)',
    authorOrInstitution: 'European Parliament and Council of the European Union',
    url: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj/eng',
    contextualNote: 'Official text of the GDPR, with particular relevance to Recital 26 (identifiability/anonymity), Article 5 (principles), Article 6 (legal bases), Article 9 (special categories), Articles 12–15 (transparency and access), Article 22 (automated decision-making), Article 25 (data protection by design), and Article 35 (DPIA).',
  },
  {
    id: 'S3',
    title: 'Press release on Case C-203/22, Dun & Bradstreet Austria',
    authorOrInstitution: 'Court of Justice of the European Union (CJEU)',
    url: 'https://curia.europa.eu/jcms/upload/docs/application/pdf/2025-02/cp250022en.pdf',
    contextualNote: 'Clarifies that under GDPR Article 15(1)(h), controllers must explain the procedure and principles actually applied in automated decisions so individuals can understand which personal data were used, how they influenced the outcome, and can challenge the result.',
  },
  {
    id: 'S4',
    title: 'Special Publication 800-226: Guidelines for Evaluating Differential Privacy Guarantees',
    authorOrInstitution: 'National Institute of Standards and Technology (NIST)',
    url: 'https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-226.pdf',
    contextualNote: 'Technical guidance on differential privacy parameters (epsilon, delta), neighbor definitions, sensitivity, composition bounds, empirical privacy audits, and utility trade-offs.',
  },
  {
    id: 'S5',
    title: 'Artificial Intelligence Risk Management Framework (AI RMF 1.0, NIST AI 100-1)',
    authorOrInstitution: 'National Institute of Standards and Technology (NIST)',
    url: 'https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf',
    contextualNote: 'Taxonomy of AI risks, classifying bias into systemic, computational/statistical, and human-cognitive sources, and setting benchmarks for explainability and risk governance.',
  },
  {
    id: 'S6',
    title: 'John Rawls',
    authorOrInstitution: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/rawls/',
    contextualNote: 'Examines Rawlsian justice as fairness: the lexical priority of equal basic liberties, fair equality of opportunity, and the difference principle (inequalities must benefit the least advantaged).',
  },
  {
    id: 'S7',
    title: 'Algorithmic Fairness',
    authorOrInstitution: 'Stanford Encyclopedia of Philosophy',
    url: 'https://plato.stanford.edu/entries/algorithmic-fairness/',
    contextualNote: 'Formal metrics of fairness (demographic parity, equalized odds, calibration), individual fairness formulations, and mathematical impossibility theorems showing inherent trade-offs.',
  },
  {
    id: 'S8',
    title: 'Fairness and Abstraction in Sociotechnical Systems',
    authorOrInstitution: 'A. D. Selbst, d. boyd, S. A. Friedler, S. Venkatasubramanian, J. Vertesi (ACM FAT* 2019)',
    url: 'https://sorelle.friedler.net/papers/sts_fat2019.pdf',
    contextualNote: 'Identifies the five sociotechnical traps when abstracting fairness into algorithmic pipelines: Framing, Portability, Formalism, Ripple Effect, and Solutionism.',
  },
  {
    id: 'S9',
    title: 'Precision Medicine',
    authorOrInstitution: 'National Human Genome Research Institute (NHGRI)',
    url: 'https://www.genome.gov/genetics-glossary/Precision-Medicine',
    contextualNote: 'Overview of genomic, environmental, and clinical data integration in targeted therapies and statistical risk scoring.',
  },
  {
    id: 'S10',
    title: 'Ethics and Governance of Artificial Intelligence for Health',
    authorOrInstitution: 'World Health Organization (WHO)',
    url: 'https://www.who.int/publications/i/item/9789240029200',
    contextualNote: 'Global guidance outlining key ethical principles for AI in health: protecting autonomy, promoting human safety and well-being, ensuring transparency and explainability, fostering responsibility, and guaranteeing equity.',
  },
  {
    id: 'S11',
    title: 'Navigating the EU AI Act (Legal Framework & FAQs)',
    authorOrInstitution: 'European Commission',
    url: 'https://digital-strategy.ec.europa.eu/en/faqs/navigating-ai-act',
    contextualNote: 'Risk categorization under the EU AI Act, including prohibited practices (such as individual predictive policing based solely on profiling) and requirements for high-risk AI systems.',
  },
  {
    id: 'S-AM',
    title: 'Data Privacy: Ethics, Decision-Making and Algorithmic Influence — Corrected Study Guide',
    authorOrInstitution: 'Course materials (corrected)',
    url: '',
    contextualNote: 'Covers ethical reasoning, consequentialism, deontology, virtue ethics, social contract theory, bounded rationality, heuristics and biases, nudging and hypernudging, digital gerrymandering, privacy self-management, and responsibility.',
  },
  {
    id: 'S12',
    title: 'Relationship Between Cybersecurity and Privacy',
    authorOrInstitution: 'NIST National Cybersecurity Center of Excellence',
    url: 'https://www.nccoe.nist.gov/relationship-between-cybersecurity-and-privacy',
    contextualNote: 'Explains how cybersecurity and privacy overlap and differ: a secure system may still use data inappropriately, and a privacy-respecting system still needs security.',
  },
  {
    id: 'S13',
    title: 'CSRC Glossary: Anonymity',
    authorOrInstitution: 'NIST Computer Security Resource Center',
    url: 'https://csrc.nist.gov/glossary/term/anonymity',
    contextualNote: 'Defines anonymity as the condition where an observer cannot identify a person within a relevant set, contingent on the observer\'s knowledge.',
  },
  {
    id: 'S15',
    title: 'EU Data Protection Legal Framework',
    authorOrInstitution: 'European Commission',
    url: 'https://commission.europa.eu/law/law-topic/data-protection/legal-framework-eu-data-protection_en',
    contextualNote: 'Overview distinguishing the EU rights to respect for private life and protection of personal data as related but distinct fundamental rights.',
  },
  {
    id: 'S16',
    title: 'Privacy-Enhancing Technologies (PETs) Draft Guidance',
    authorOrInstitution: 'UK Information Commissioner\'s Office (ICO)',
    url: 'https://ico.org.uk/media2/migrated/4021464/chapter-5-anonymisation-pets.pdf',
    contextualNote: 'Technical guidance on categories of privacy-enhancing technologies including differential privacy, secure multiparty computation, homomorphic encryption, and federated learning.',
  },
  {
    id: 'S18',
    title: 'Digital Identity Guidelines (SP 800-63-4)',
    authorOrInstitution: 'NIST',
    url: 'https://pages.nist.gov/800-63-4/sp800-63.html',
    contextualNote: 'Guidelines for identity proofing, authentication, and federation — distinguishing identity management from security and privacy.',
  },
  {
    id: 'S19',
    title: 'Threat Modeling Tool Threats (STRIDE)',
    authorOrInstitution: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/azure/security/develop/threat-modeling-tool-threats',
    contextualNote: 'Reference for the STRIDE threat categories: Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, and Elevation of Privilege.',
  },
  {
    id: 'S20',
    title: 'LINDDUN Privacy Threat Modeling',
    authorOrInstitution: 'LINDDUN.org',
    url: 'https://linddun.org/',
    contextualNote: 'Framework for identifying privacy threats by mapping people, processes, data stores and information flows, then applying seven privacy-specific threat categories.',
  },
  {
    id: 'S21',
    title: 'LINDDUN Threat Categories',
    authorOrInstitution: 'LINDDUN.org',
    url: 'https://linddun.org/linddun-go-categories/',
    contextualNote: 'Describes the seven LINDDUN categories: Linking, Identifying, Non-repudiation, Detecting, Disclosure of information, Unawareness, and Non-compliance.',
  },
  {
    id: 'S22',
    title: 'LINDDUN PRO',
    authorOrInstitution: 'LINDDUN.org',
    url: 'https://linddun.org/pro/',
    contextualNote: 'Structured privacy threat modeling approach built around data-flow diagrams, distinct from the lighter collaborative LINDDUN GO method.',
  },
  {
    id: 'S23',
    title: 'Guidelines 4/2019 on Data Protection by Design and by Default (Article 25)',
    authorOrInstitution: 'European Data Protection Board (EDPB)',
    url: 'https://www.edpb.europa.eu/documents/guideline/guidelines-42019-on-article-25-data-protection-by-design-and-by-default_en',
    contextualNote: 'Guidelines on implementing data protection by design and by default, including measures to minimize data and integrate safeguards into processing.',
  },
  {
    id: 'S24',
    title: 'A Privacy Threat Analysis Framework: Supporting the Elicitation and Fulfillment of Privacy Requirements',
    authorOrInstitution: 'M. Deng, K. Wuyts, R. Scandariato, B. Preneel, W. Joosen',
    url: 'https://cosicdatabase.esat.kuleuven.be/backend/publications/files/journal/1412',
    contextualNote: 'Introduces the distinction between hard privacy (avoiding data disclosure) and soft privacy (controlling disclosed data through rules and accountability).',
  },
  {
    id: 'S25',
    title: 'A Terminology for Talking About Privacy by Data Minimization',
    authorOrInstitution: 'A. Pfitzmann and M. Hansen',
    url: 'https://www.ietf.org/archive/id/draft-hansen-privacy-terminology-00.html',
    contextualNote: 'Standard terminology for anonymity, pseudonymity, unlinkability, and unobservability in data-minimization contexts.',
  },
];
